const state={mood:'funny',time:'1-2 hours',service:'Any service',type:'any',saved:[],current:catalog[0]};
const qs=s=>document.querySelector(s);const moodBox=qs('#moods'),timeBox=qs('#times'),serviceBox=qs('#services');
moods.forEach(([id,icon,label],i)=>moodBox.insertAdjacentHTML('beforeend',`<button class="mood ${i===0?'selected':''}" data-value="${id}"><i>${icon}</i>${label}</button>`));
times.forEach((name,i)=>timeBox.insertAdjacentHTML('beforeend',`<button class="segment ${i===2?'selected':''}" data-value="${name}">${name}</button>`));
services.forEach((name,i)=>serviceBox.insertAdjacentHTML('beforeend',`<button class="service ${i===6?'selected':''}" data-value="${name}">${name}</button>`));
function select(group,selector,key){group.addEventListener('click',e=>{const button=e.target.closest(selector);if(!button)return;group.querySelectorAll(selector).forEach(x=>x.classList.remove('selected'));button.classList.add('selected');state[key]=button.dataset.value})}select(moodBox,'.mood','mood');select(timeBox,'.segment','time');select(serviceBox,'.service','service');select(qs('#types'),'button','type');
function candidates(){const genre=qs('#genre').value,rating=qs('#rating').value;let list=catalog.filter(item=>(item.moods.includes(state.mood)||Math.random()>.55)&&(state.service==='Any service'||item.service===state.service||item.service==='Any service')&&(state.type==='any'||item.type===state.type)&&(genre==='all'||item.genres.includes(genre))&&(rating==='all'||item.rating===rating));return list.length?list:catalog}
function showPick(item){state.current=item;qs('#title').textContent=item.title;qs('#meta').textContent=`${item.year}  •  ${item.time}  •  ${item.rating}`;qs('#description').textContent=item.desc;qs('#tags').innerHTML=item.genres.map(g=>`<span>${g}</span>`).join('')+`<span>${item.service}</span>`;qs('#poster').className=`poster ${item.art}`;qs('#poster').innerHTML=`<div class="poster-text"><small>ORIGINAL PICK</small><strong>${item.title.replace(' ','<br>')}</strong></div><div class="poster-orb"></div>`;qs('#match').textContent=92+Math.floor(Math.random()*7);qs('#result').classList.add('visible');qs('#result').scrollIntoView({behavior:'smooth',block:'center'})}
function pick(){const list=candidates();showPick(list[Math.floor(Math.random()*list.length)])}qs('#pickButton').onclick=pick;qs('#again').onclick=pick;
function cards(items,target){target.innerHTML=items.map(item=>`<article class="mini-card"><div class="mini-art ${item.art}"><span>${item.type==='show'?'SERIES':'FILM'}</span></div><h3>${item.title}</h3><p>${item.time} • ${item.genres[0]}</p><button data-title="${item.title}">View pick</button></article>`).join('');target.querySelectorAll('button').forEach(btn=>btn.onclick=()=>showPick(catalog.find(x=>x.title===btn.dataset.title)))}cards(catalog.slice(1,6),qs('#movieRow'));
qs('#shuffle').onclick=()=>cards([...catalog].sort(()=>Math.random()-.5).slice(0,5),qs('#movieRow'));
qs('#save').onclick=()=>{const item=state.current;if(!state.saved.some(x=>x.title===item.title)){state.saved.push(item);renderSaved();toast(`${item.title} saved to your watchlist.`)}else toast('Already saved to your watchlist.')};
function renderSaved(){qs('#savedCount').textContent=state.saved.length;qs('#savedEmpty').style.display=state.saved.length?'none':'block';cards(state.saved,qs('#savedRow'))}function toast(message){const t=qs('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
qs('#trailer').onclick=()=>qs('#trailerModal').classList.add('open');qs('#closeTrailer').onclick=()=>qs('#trailerModal').classList.remove('open');qs('#trailerModal').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.classList.remove('open')};
